---
- name: Configure http-server-sockets.conf
  ansible.builtin.template:
    dest: "{{ mule_home }}/mule/conf/http-server-sockets.conf"
    src: "templates/http-server-sockets.conf.j2"
    owner: "{{ mule_user }}"
    group: "{{ mule_group }}"
    mode: 0644

- name: Append extended configuration to http-server-sockets.conf
  ansible.builtin.blockinfile:
    path: "{{ mule_home }}/mule/conf/http-server-sockets.conf"
    block: "{{ http_server_extended_configuration }}"
  when: 
    - http_server_extended_configuration is defined
    - http_server_extended_configuration | length > 0

- name: Configure scheduler-pools.conf
  ansible.builtin.template:
    dest: "{{ mule_home }}/mule/conf/scheduler-pools.conf"
    src: "templates/scheduler-pools.conf.j2"
    owner: "{{ mule_user }}"
    group: "{{ mule_group }}"
    mode: 0644

- name: Append extended configuration to scheduler-pools.conf
  ansible.builtin.blockinfile:
    path: "{{ mule_home }}/mule/conf/scheduler-pools.conf"
    block: "{{ scheduler_pools_extended_configuration }}"
  when: 
    - scheduler_pools_extended_configuration is defined
    - scheduler_pools_extended_configuration | length > 0

- name: Configure wrapper.conf
  ansible.builtin.template:
    dest: "{{ mule_home }}/mule/conf/wrapper.conf"
    src: "templates/wrapper.conf.j2"
    owner: "{{ mule_user }}"
    group: "{{ mule_group }}"
    mode: 0644
  
- name: Append extended configuration to wrapper.conf
  ansible.builtin.blockinfile:
    path: "{{ mule_home }}/mule/conf/wrapper.conf"
    block: "{{ wrapper_extended_configuration }}"
  when: 
    - wrapper_extended_configuration is defined
    - wrapper_extended_configuration | length > 0

- name: Ensure systemd service file exists
  ansible.builtin.template:
    dest: "/usr/lib/systemd/system/mule.service"
    src: "templates/mule.service.j2"
    owner: "root"
    group: "root"
    mode: 0644

- name: Ensure systemd service file is correctly activated
  ansible.builtin.file:
    path: "/etc/systemd/system/multi-user.target.wants/mule.service"
    src: "/usr/lib/systemd/system/mule.service"
    state: link

- name: Ensure mule home has right permissions
  ansible.builtin.file:
    path: "{{ mule_home }}"
    recurse: yes
    owner: "{{ mule_user }}"
    group: "{{ mule_group }}"
