---
- name: Configure http-server-sockets.conf
  ansible.builtin.template:
    dest: "{{ mule_home }}/mule/conf/http-server-sockets.conf"
    src: "../templates/http-server-sockets.conf.j2"
    owner: "{{ mule_user }}"
    group: "{{ mule_group }}"
    mode: 0755

- name: Configure scheduler-pools.conf
  ansible.builtin.template:
    dest: "{{ mule_home }}/mule/conf/scheduler-pools.conf"
    src: "../templates/scheduler-pools.conf.j2"
    owner: "{{ mule_user }}"
    group: "{{ mule_group }}"
    mode: 0755

- name: Configure wrapper.conf
  ansible.builtin.template:
    dest: "{{ mule_home }}/mule/conf/wrapper.conf"
    src: "../templates/wrapper.conf.j2"
    owner: "{{ mule_user }}"
    group: "{{ mule_group }}"
    mode: 0755

- name: Copy file wrapper-additional.conf
  ansible.builtin.template:
    dest: "{{ mule_home }}/mule/conf/wrapper-additional.conf"
    src: "../templates/wrapper-additional.conf.j2"
    owner: "{{ mule_user }}"
    group: "{{ mule_group }}"
    mode: 0755

- name: Ensure systemd service file exists
  ansible.builtin.template:
    dest: "/usr/lib/systemd/system/mule.service"
    src: "../templates/mule.service.j2"

- name: Ensure systemd service file is correctly activated
  ansible.builtin.file:
    path: "/etc/systemd/system/multi-user.target.wants/mule.service"
    src: "/usr/lib/systemd/system/mule.service"
    state: link

- name: Ensure {{ mule_home }} has right permissions
  ansible.builtin.file:
    path: "{{ mule_home }}"
    recurse: yes
    owner: "{{ mule_user }}"
    group: "{{ mule_group }}"
