---

- name: Configure Mule wrapper.conf
  ansible.builtin.lineinfile:
    dest: "{{ mule_home }}/mule/conf/wrapper.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^wrapper.java.command.?=.+$"
      line: "wrapper.java.command={{ mule_wrapper_java_command }}"
    - regexp: "^wrapper.java.initmemory.?=.+$"
      line: "wrapper.java.initmemory={{ mule_wrapper_java_initmemory }}"
    - regexp: "^wrapper.java.maxmemory.?=.+$"
      line: "wrapper.java.maxmemory={{ mule_wrapper_java_maxmemory }}"
    - regexp: "^wrapper.startup.timeout.?=.+$"
      line: "wrapper.startup.timeout={{ mule_wrapper_startup_timeout }}"
    - regexp: "^wrapper.console.format.?=.+$"
      line: "wrapper.console.format={{ mule_wrapper_console_format }}"
    - regexp: "^wrapper.console.loglevel.?=.+$"
      line: "wrapper.console.loglevel={{ mule_wrapper_console_loglevel }}"
    - regexp: "^wrapper.logfile.?=.+$"
      line: "wrapper.logfile={{ mule_wrapper_logfile }}"
    - regexp: "^wrapper.logfile.format.?=.+$"
      line: "wrapper.logfile.format={{ mule_wrapper_logfile_format }}"
    - regexp: "^wrapper.logfile.loglevel.?=.+$"
      line: "wrapper.logfile.loglevel={{ mule_wrapper_logfile_loglevel }}"
    - regexp: "^wrapper.logfile.maxsize.?=.+$"
      line: "wrapper.logfile.maxsize={{ mule_wrapper_logfile_maxsize }}"
    - regexp: "^wrapper.logfile.maxfiles.?=.+$"
      line: "wrapper.logfile.maxfiles={{ mule_wrapper_logfile_maxfiles }}"
    - regexp: "^wrapper.syslog.loglevel.?=.+$"
      line: "wrapper.syslog.loglevel={{ mule_wrapper_syslog_loglevel }}"

- name: Ensure systemd service file exists
  ansible.builtin.template:
    dest: "/usr/lib/systemd/system/mule.service"
    src: "templates/mule.service.j2"
    owner: "root"
    group: "root"
    mode: 0644

- name: Ensure systemd service file is correctly activated
  ansible.builtin.file:
    path: "/etc/systemd/system/multi-user.target.wants/mule.service"
    src: "/usr/lib/systemd/system/mule.service"
    state: link

- name: Ensure mule home has right permissions
  ansible.builtin.file:
    path: "{{ mule_home }}"
    recurse: yes
    owner: "{{ mule_user }}"
    group: "{{ mule_group }}"
