---
- name: Define mule_version.
  ansible.builtin.set_fact:
    mule_version: "{{ __mule_version }}"
  when: mule_version is not defined

- name: Execute prepare tasks
  ansible.builtin.include_tasks: prepare.yml

- name: Download and install Mule
  ansible.builtin.include_tasks: install.yml

- name: Configure Mule
  ansible.builtin.include_tasks: configure.yml

- name: Restart Mule
  ansible.builtin.service:
    name: "mule.service"
    state: restarted
    sleep: 5
  when: mule_restart_handler_enabled