---
- name: Create Mule Group
  ansible.builtin.user:
    name: "{{ mule_group }}"
  when: mule_create_user | default(false) | bool

- name: Create Mule User
  ansible.builtin.user:
    name: "{{ mule_user }}"
    shell: /bin/bash
    group: "{{ mule_group }}"
    create_home: true
    home: "/opt/mule"
  when: mule_create_user | default(false) | bool